server:
  port: 80

dubbo:
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.146.130:2181
  monitor:
    protocol: registry
  application:
    name: web



spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
