server:
  port: 8100
spring:
  #开启热部署
  devtools:
    restart:
      enabled: true
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.146.130:3306/money?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  # redis 配置
  redis:
    # 地址
    host: 192.168.146.130
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 20s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

dubbo:
  application:
    name: dataservice
  #注册中心协议和地址
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.146.130:2181
  #通信规则
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry

#mybatis对mapper.xml的扫描添加
mybatis:
  mapper-locations: classpath:mapper/*.xml  #你的mapper.xml文件所在位置
  configuration:
    map-underscore-to-camel-case: true #开启mybatis的驼峰命名法识别

# 日志配置
logging:
  level:
    com.scrh.money.dataservice.mapper: debug
    org.springframework: warn
